[package]
name = "blokaz"
version = "1.0.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = "2.13.1"
game_components_minigame = { git = "https://github.com/provable-games/game-components", tag = "v2.13.1" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0-alpha.3" }
openzeppelin_interfaces = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0-alpha.3" }

[dev-dependencies]
cairo_test = "2.13.1"

[[target.starknet-contract]]
